// api/getReview.js

const VISIT_OPENERS = [
  "Visited Royal Cafe and Dining at IP Sigra Mall recently and it completely exceeded my expectations",
  "Had been hearing great things about Royal Cafe and Dining in Sigra and finally visited last weekend",
  "A colleague recommended Royal Cafe and Dining for our team lunch and every single person at the table loved it",
  "Stumbled upon Royal Cafe and Dining on the second floor of IP Sigra Mall and it turned out to be a fantastic discovery",
  "My family has been visiting Royal Cafe and Dining regularly for the past few months and every visit has been wonderful",
  "Tried Royal Cafe and Dining for the first time on a friend's insistence and I am so glad I listened",
  "Was looking for a good restaurant in Sigra for a special occasion and Royal Cafe and Dining delivered on every front",
  "Celebrated a small get-together at Royal Cafe and Dining and the experience was genuinely memorable",
  "Have been going to Royal Cafe and Dining ever since it opened and it keeps getting better with every visit",
  "A birthday party for my nephew led us to Royal Cafe and Dining and we have been coming back ever since",
  "Found Royal Cafe and Dining through Dineout and the reviews did not do it full justice, it is even better in person",
  "Tried several restaurants in Varanasi before landing at Royal Cafe and Dining, and now there is simply no going back",
  "Visited Royal Cafe and Dining for a ring ceremony dinner and the entire family was thoroughly impressed",
  "Had our kitty party at Royal Cafe and Dining last month and everyone agreed it was the best choice we could have made",
  "Discovered Royal Cafe and Dining while browsing Swiggy and decided to dine in instead, best decision ever",
  "My wife and I visited Royal Cafe and Dining for our anniversary dinner and it was absolutely perfect",
  "Heard about Royal Cafe and Dining from three different people and each time I was told it is special, they were all right",
  "Came to Royal Cafe and Dining for a quick lunch and ended up staying three hours because the food and vibe were too good to leave",
  "Was searching for a restaurant in Varanasi that genuinely offers diverse cuisine and Royal Cafe and Dining is exactly that",
  "A family friend celebrated her daughter's birthday at Royal Cafe and Dining and we attended as guests, it was lovely",
  "Needed a nice spot for a marriage anniversary celebration in Varanasi and Royal Cafe and Dining was recommended by everyone",
  "Tried Royal Cafe and Dining after spotting it on the second floor of IP Sigra Shopping Mall and it blew me away",
  "Booked via EazyDiner for the first time at Royal Cafe and Dining and the discount made it even sweeter",
  "Came with a group of friends to Royal Cafe and Dining and we all agreed it is the best dining experience in Sigra",
  "Was celebrating a promotion and wanted something special in Varanasi, Royal Cafe and Dining was the obvious choice",
  "My parents visited Royal Cafe and Dining on my recommendation and called me immediately to say it was outstanding",
  "Took my office team for a celebration lunch at Royal Cafe and Dining and every dish we ordered was a hit",
  "Had been wanting to try Royal Cafe and Dining for months and the visit finally lived up to all the anticipation",
  "A random weekday dinner at Royal Cafe and Dining turned into one of my favourite food memories in Varanasi",
  "Visited Royal Cafe and Dining with my in-laws and the food and service made an excellent impression on everyone",
  "My brother insisted we try Royal Cafe and Dining for his farewell dinner and it was the perfect send-off meal",
  "Spent a lazy Sunday afternoon at Royal Cafe and Dining and left feeling like the day had been thoroughly well spent",
  "Had been skeptical about trying a new restaurant but Royal Cafe and Dining converted me instantly from the first bite",
  "Took my grandmother to Royal Cafe and Dining and she declared it the best meal she had had in years in Varanasi",
  "A work project celebration brought our team to Royal Cafe and Dining and it became an evening everyone remembered fondly",
  "Walked past Royal Cafe and Dining many times before finally going in and immediately regretted not visiting sooner",
  "My cousin visiting from Delhi was impressed by Royal Cafe and Dining and said the food matched top restaurants back home",
  "Planned a surprise dinner for my husband at Royal Cafe and Dining and it turned into the most romantic evening",
  "Every person I have brought to Royal Cafe and Dining for the first time has had the same reaction, pure amazement",
  "Used to wonder what all the fuss about Royal Cafe and Dining was until I experienced it firsthand and understood completely",
  "Visited on a busy Friday evening and despite the crowd the experience was seamless and the food was perfect",
  "My daughter specifically requested Royal Cafe and Dining for her graduation dinner and it delivered exactly what she hoped for",
  "Discovered Royal Cafe and Dining through a colleague's Instagram post and booked a table the very same evening",
  "Came for a quick meal and ended up ordering desserts twice because everything at Royal Cafe and Dining was too good to stop",
  "My neighbours have been loyal fans of Royal Cafe and Dining for over a year and I finally understand why after my first visit",
  "Tried Royal Cafe and Dining on a whim during a shopping trip to IP Sigra Mall and it was the highlight of the day",
  "Had our engagement celebration dinner at Royal Cafe and Dining and could not have chosen a more perfect venue",
  "Visited Royal Cafe and Dining after reading countless positive reviews and found that every single one was completely accurate",
  "Was introduced to Royal Cafe and Dining by my doctor who mentioned it as the best restaurant near IP Sigra and he was absolutely right",
  "Spent my work anniversary evening at Royal Cafe and Dining and it was exactly the kind of celebration the occasion deserved"
];

const FOOD_PRAISE = [
  "The 3 Idiot Paneer Tikka is an absolute must-order, easily one of the best starters I have had in Varanasi",
  "The Chicken Malai Tikka here is melt-in-the-mouth tender and the marinade is exceptionally well-balanced",
  "Drums of Heaven are perfectly crispy and the sauce is absolutely addictive, ordered a second portion immediately",
  "The Dahi Ke Kebab melts in your mouth and has a subtlety that really shows the kitchen knows what it is doing",
  "Paneer Malai Tikka was creamy, delicate, and cooked to perfection on the tandoor, a beautiful starter",
  "Hara Bhara Kebab was vibrant, well-spiced, and genuinely one of the freshest tasting vegetarian starters I have encountered",
  "The Veg Seekh Kebab here is surprisingly meaty in texture and the smoky char from the tandoor is wonderful",
  "Stuffed Mushroom Tikka is a creative and delicious starter, the filling inside each mushroom is beautifully seasoned",
  "Chicken Seekh Kebab arrived sizzling from the tandoor and the juicy, well-spiced mince was genuinely outstanding",
  "The Afgani Soya Chaap is rich, creamy, and cooked with a level of care you rarely get in restaurants in Varanasi",
  "Chicken Afghani is tender and aromatic, the marinade is subtle and refined, a genuinely excellent tandoori dish",
  "The Veg Tandoori Platter is an RCD Special that showcases the best of their tandoor section all on one impressive plate",
  "Tandoori Chicken Platter is a crowd-pleaser done perfectly, the char and marinade are genuinely impressive",
  "Paneer Tikka was beautifully charred on the outside and soft inside, paired perfectly with the mint chutney here",
  "Chicken Lollipop arrived with a beautiful glaze and the meat was perfectly cooked right through, absolutely addictive",
  "Schezwan Crispy Chicken is punchy, well-fried, and the Schezwan sauce has a genuine depth of flavour",
  "Chicken 65 was crispy, spicy, and one of the most well-executed versions of this classic I have had anywhere",
  "Crispy Honey Potato is a deceptively simple dish that is shockingly addictive, everyone at the table fought over the last piece",
  "The American Corn Salt and Pepper is light, fresh, and a brilliant vegetarian starter option",
  "Cheese Balls arrived golden and gooey with a beautifully seasoned crust, perfect with the dipping sauce",
  "Paneer Kathi Roll is filling, well-spiced, and the roti wrap is soft and fresh, a satisfying choice at any time",
  "Chicken Kathi Roll was packed with well-marinated chicken and fresh vegetables, genuinely excellent street-food style cooking",
  "The Singapore Noodles are full of flavour with a light spice and excellent wok char, one of my go-to orders here",
  "Chicken Hakka Noodles here are perfectly cooked, not clumped, well-seasoned, and come out piping hot every time",
  "American Chopsuey is the ultimate comfort Chinese dish and Royal Cafe and Dining does it wonderfully with a crispy noodle base",
  "Chilli Garlic Noodles had the perfect level of heat and the garlic flavour was aromatic without being overpowering",
  "Pan Fried Noodles are brilliantly executed here, crispy on the edges yet soft in the centre, outstanding texture",
  "Chicken Manchurian in the gravy version is rich, tangy, and the chicken balls are tender inside with a slightly crisp coating",
  "Garlic Chicken is a simple dish done excellently, the sauce is deeply garlicky and the chicken is wonderfully tender",
  "Lemon Garlic Chicken is bright, tangy, and perfectly balanced, a lighter Chinese option that is genuinely satisfying",
  "Chilli Paneer here is crisp on the outside, soft inside, and the sauce hits all the right notes of spice and tang",
  "Chilly Mushroom was well-cooked with a bold sauce and the mushrooms retained their texture beautifully",
  "Schezwan Fried Rice is punchy and fragrant, tossed perfectly with visible vegetables and excellent wok flavour",
  "Egg Fried Rice came out perfectly separated, not greasy at all, and the seasoning was absolutely spot on",
  "The Veg Chinese Combo is fantastic value, a generous spread of noodles and main that gives you the best of both",
  "The Smoked Chicken Pizza is honestly one of the best pizzas I have had outside of a dedicated pizzeria",
  "Chicken Cheese Burst Pizza lives up completely to its name, the cheese pull on this is genuinely spectacular",
  "Veg Cheese Burst Pizza is perfectly baked with a beautiful crust and the cheese burst centre is indulgent and delicious",
  "Smoked Paneer Pizza is a Chef Special that showcases genuinely creative flavour pairing, the smokiness is beautifully executed",
  "Tandoori Chicken Pizza has a wonderful combination of classic pizza flavours with Indian spices, a brilliant fusion dish",
  "The Chicken Barbeque Pizza has a beautifully smoky, sweet-tangy topping and the base is consistently well-baked",
  "Veg Barbeque Pizza is a great choice for vegetarians, the toppings are generous and the barbecue sauce is excellent",
  "Spaghetti Aglio E Olio is light, garlicky, and beautifully done without being greasy at all",
  "Baked Penne Pasta is comforting, cheesy, and the sauce has a richness and depth that makes it hard to stop eating",
  "Club Chicken Triple Decker Sandwich is massive, generously filled, and absolutely delicious in every layer",
  "Veg Triple Decker Sandwich is a Chef Special that is packed with flavour and fresh ingredients, a brilliant lunch option",
  "Paneer Tikka Sandwich combines the best of tandoori flavours with a fresh sandwich, a genuinely creative and satisfying dish",
  "Chicken Tikka Sandwich is well-seasoned, fresh, and a wonderful lighter option that does not compromise on flavour",
  "Veg Cheese Corn Sandwich is simple comfort food done perfectly, the sweetness of corn with the melt of cheese is wonderful",
  "Murgh Handilazeez is a beautiful slow-cooked dish with complexity and warmth in every spoonful",
  "The Chicken Rara is an RCD Special that is deeply flavourful and the texture of the gravy is exactly right",
  "Chef Chicken from the RCD Specials menu is something every first-time visitor absolutely must try",
  "Mutton Rogan Josh here is aromatic, rich, and the slow-cooked mutton falls apart beautifully, genuinely exceptional",
  "Matka Mutton Biryani is rich, slow-cooked, and bursting with flavour in every single bite",
  "The Mutton Rara is an RCD Special with an extraordinarily bold and complex gravy that deserves its own category entirely",
  "Chicken Kali Mirch has a bold pepper flavour that is beautifully balanced without being overwhelming, a refined dish",
  "Achari Murgh has a tangy, pickle-spiced gravy that is genuinely unique and outstanding paired with a warm Garlic Naan",
  "Palak Chicken is well-balanced with a fresh spinach gravy that is not too heavy, a beautifully executed dish",
  "Chicken Korma is creamy and subtly spiced, the kind of dish that feels genuinely indulgent without being too rich",
  "Chicken Butter Masala here is silky, well-spiced, and the tomato base has a richness that pairs perfectly with naan",
  "Chicken Lababdar has a wonderful charred onion and tomato gravy with a depth of flavour that is hard to match",
  "Kadai Chicken is bold, rustic, and the freshly ground masalas in the gravy are very much alive in every bite",
  "Chicken Dhaniya-adraki is a fragrant coriander and ginger dish that is light yet deeply flavourful, a standout on the menu",
  "Mutton Curry here is slow-cooked the right way, the spices are beautifully integrated and the mutton is wonderfully tender",
  "Palak Paneer here is smooth, well-seasoned, and uses real fresh ingredients that you can taste immediately",
  "Paneer Hyderabadi is cooked just right with a perfect balance of spice and richness",
  "Paneer Butter Masala has a velvety tomato gravy that is rich without being cloying, beautifully balanced",
  "Shahi Paneer is truly regal in its flavour, the creamy gravy is well-spiced and the paneer is fresh and soft",
  "Kadai Paneer has a wonderfully rustic flavour with the freshness of capsicum and tomatoes coming through clearly",
  "Paneer Dhaniya-adraki is a fragrant, lighter option that is a refreshing change from the richer paneer gravies",
  "Malai Kofta here is one of the creamiest and most well-balanced versions I have had in any restaurant",
  "Paneer Lababdar has a wonderfully smoky, charred flavour in the gravy that sets it apart from the usual version",
  "Dal Palak is a brilliantly healthy and comforting combination, the lentils and spinach are cooked together perfectly",
  "Punjabi Dal Tadka here is exactly how it should be, smoky tempering on top of a thick, well-cooked dal",
  "Corn Palak was a delightful combination I had not tried before and it is now one of my favourite vegetarian dishes",
  "Mushroom Do Pyaza is a rich, onion-forward mushroom dish that is genuinely excellent paired with Lachha Paratha",
  "Bhindi Masala here is perfectly cooked, the okra is not slimy at all and the masala is wonderfully fragrant",
  "Aloo Jeera is simple comfort food done brilliantly, the tempering is perfect and the potatoes are cooked just right",
  "The Kashmiri Naan is soft, slightly sweet, and pairs wonderfully with the richer gravies on the menu",
  "Garlic Naan paired perfectly with the Murgh Handilazeez and we finished with a Firni Faluda Shake, an unforgettable meal",
  "Chicken Keema Kulcha is a hearty and satisfying combination that pairs brilliantly with the chutneys here",
  "Lachha Paratha here is perfectly layered, crispy on the outside, and soft inside, genuinely excellent bread",
  "Cheese Naan is indulgent and delicious, the cheese melts beautifully inside and the bread is cooked perfectly",
  "Missi Roti is earthy, flavourful, and the kind of wholesome bread that makes simple dals taste extraordinary",
  "Stuffed Kulcha is generously filled and perfectly cooked on the tandoor, a great bread option for any main course",
  "The Bamboo Chicken Dum Biryani is genuinely outstanding, the aroma alone is worth the visit",
  "Banarasi Soya Dum Biryani is a brilliant vegetarian biryani with great depth of flavour unique to this kitchen",
  "Chicken Biryani here is dum-cooked properly, the rice is perfectly separated and the flavours are deeply integrated",
  "Mutton Biryani is layered, aromatic, and the mutton pieces are tender throughout, an excellent version of this classic",
  "Kashmiri Pulao is a beautifully fragrant sweet and savoury rice dish that is unlike anything else on the menu",
  "Hot and Sour Soup here is perfectly balanced between heat and tang, a great starter for the meal",
  "Sweet Corn Soup is comforting, thick, and well-seasoned, the kind of soup that makes you order a second bowl",
  "Manchow Soup has a beautifully crispy noodle topping and the broth is deeply flavoured, one of the best versions around",
  "Cream of Tomato Soup is silky, rich, and beautifully seasoned, comfort in a bowl on any day",
  "Lemon Coriander Soup is light, fresh, and genuinely restorative, a perfect way to start any meal here",
  "V Fries from the RCD Special menu are dangerously good, crispy with a unique seasoning that keeps you reaching for more",
  "Cheesy French Fries are indulgent and generously loaded, the cheese sauce is thick and perfectly seasoned",
  "Herby Cheese Garlic Bread has a beautiful herbed crust and generous garlic butter, the best bread snack on the menu",
  "Cheese Chilli Toast is a wonderful snack, the heat of green chillies with the melt of cheese on crisp toast is perfect",
  "Paneer Kurkure is crispy, well-spiced, and addictive, a brilliant snack that pairs excellently with a cold frappe",
  "Assorted Vegetable Pakodas are golden, crispy, and come with a chutney that elevates them beautifully",
  "The Cafe Hazelnut is beautifully aromatic and the hazelnut syrup is not overpowering, perfectly balanced",
  "Popcorn Caramel Latte is a delightfully quirky drink that actually works wonderfully, a real conversation starter",
  "Irish Coffee here is made properly with a genuine kick and beautifully frothed cream on top",
  "The Affogato is a classic done with precision, the shot of Espresso over the ice cream is perfectly executed",
  "Brownie Blended Coffee is thick, rich, and indulgent, the kind of cold coffee that doubles as a dessert",
  "Frappe with Cream and Cookies is a wonderfully indulgent drink, the cookies add a delightful crunch to every sip",
  "Blended Mint Mocha is a refreshing and creative combination, the mint cuts through the chocolate beautifully",
  "Caramel Frappe here is thick, sweet, and perfectly blended, one of the most popular drinks for good reason",
  "Hazelnut Frappe is aromatic and creamy, the hazelnut flavour is present throughout without being artificial tasting",
  "Peach Ice Tea is refreshing and light, the kind of drink that pairs beautifully with a heavier main course",
  "Lychee Ice Tea is delicate and floral, genuinely one of the most refreshing drinks I have had in any cafe in Varanasi",
  "Hot Chocolate Truffle is indulgent, thick, and has a depth of chocolate flavour that the regular hot chocolate cannot match",
  "Ginger Honey Tea is soothing, perfectly balanced, and ends any meal on a warm and comforting note",
  "Assam Tea here is properly brewed, strong, and served at the right temperature with good quality tea leaves",
  "The Firni Faluda Shake is a signature creation that is sweet, creamy, and completely unforgettable",
  "Red Velvet Shake is thick, indulgent, and exactly the kind of dessert drink that makes you forget everything else",
  "Rasmalai Lassi is a uniquely Banarasi creation that is sweet, cooling, and genuinely special",
  "Rasbhari Rasmalai Shake is a genius creation, dessert and drink in one and it is absolutely wonderful",
  "Rose Faluda Shake is beautifully floral, the faluda adds a wonderful texture and the rose flavour is perfectly calibrated",
  "Masala Badam Shake is warming, nutty, and has a spiced depth that makes it unlike any other shake on the menu",
  "Mango Lassi here is thick and pulpy with real mango flavour, a classic done absolutely right",
  "Oreo Shake is gloriously indulgent and the Oreo crumble throughout the thick shake makes every sip exciting",
  "Kulfi Shake captures the flavour of traditional kulfi in a cold shake perfectly, a brilliant fusion creation",
  "Kitkat Shake is a playful and genuinely delicious creation with real Kitkat pieces blended throughout",
  "Banana Caramel Shake is a wonderful combination, the caramel sweetness with banana makes for an outstanding dessert drink",
  "Coconut Shake is fresh, light, and subtly sweet, a refreshing change from the richer shake options on the menu",
  "Fruit Punch Shake is vibrant, colourful, and genuinely refreshing, a great choice for those who prefer lighter flavours",
  "Pinacolada Shake is creamy, tropical, and transports you somewhere far more relaxing with every single sip",
  "Spicy Mango Mojito is a brilliant summer drink with just the right level of heat and tang",
  "Passion Fruit Mojito is refreshing and beautifully balanced, a must-have on any visit",
  "Blue Hawaiian is a visually stunning and genuinely delicious mocktail with a tropical sweetness that is hard to resist",
  "Kala Khatta Mojito is a brilliant desi twist on the classic mojito, the jamun flavour is bold and wonderfully nostalgic",
  "Watermelon Mojito is light, fresh, and the kind of drink that makes you feel genuinely cool on a warm day",
  "Green Apple Fizz is crisp, tart, and the carbonation makes it the most refreshing mocktail option on the menu",
  "Raspberry Mojito is tart, sweet, and beautifully garnished, a lovely drink that goes well with any of the starters",
  "Chilli Guava Mojito is a creative and brilliant combination, the guava sweetness with chilli heat is genuinely inspired",
  "Masala Lemonade is tangy, spiced, and perfectly balanced, a wonderful desi mocktail that never disappoints",
  "Orange Blast is refreshing and vibrant, packed with real orange flavour and a pleasant fizz throughout",
  "Hot Brownie Sizzler arrived at the table sizzling and it was as dramatic as it was delicious, pure indulgence",
  "The Jar Ice Creams come in gorgeous flavours and are the perfect ending to a wonderful meal",
  "The Choco Lava Cake at ninety-nine rupees is outstanding value and the lava flow was perfect every single time",
  "Gulab Jamun here are soft, perfectly soaked, and served warm, a classic dessert executed flawlessly",
  "Hot Brownie Sundae is a beautifully assembled dessert with warm brownie, cold ice cream, and rich chocolate sauce",
  "Brownie with Chocolate is simple but perfectly executed, the brownie is fudgy and the chocolate sauce is genuinely rich",
  "Masala Papad here is perfectly roasted with a fresh topping of onions and tomatoes, a classic starter done right",
  "Pineapple Raita is a refreshing and sweet accompaniment that balances the richer gravies on the menu beautifully",
  "The Chicken Tikka Masala here has a depth of flavour that makes it genuinely one of the most satisfying dishes on the menu",
  "Veg Crispy Noodles with a light sauce is a great sharing snack that the whole table always reaches for first",
  "Soya Chaap Tikka has a beautiful char and the cream marinade makes every bite genuinely indulgent",
  "Peri Peri Chicken here has a beautiful smoky heat that builds pleasantly through each bite",
  "Chicken Pasta in a creamy white sauce is indulgent, well-seasoned, and the pasta is cooked to perfect al dente",
  "The Veg Kolhapuri has a robustly spiced gravy that is genuinely bold and pairs perfectly with a simple plain naan"
];

const AMBIENCE_STAFF = [
  "The ambience on the second floor is cosy, well-lit, and has a very welcoming energy throughout",
  "Staff here is exceptionally friendly and genuinely attentive without being intrusive at any point",
  "The TV setup for sports makes it a perfect spot to catch a match while having an excellent meal",
  "Service was prompt and every dish arrived at the right temperature which is something a lot of restaurants miss",
  "The interiors are clean, tastefully done, and the seating is comfortable even for long meals",
  "The staff remembered our preferences from a previous visit which is a level of personal care you rarely get",
  "Every team member here carries a genuine smile and the warmth in the service is something you feel immediately",
  "The TV screens streaming entertainment make waiting for your food an enjoyable experience rather than a boring one",
  "Pricing is very reasonable for the quality of food and service you receive at Royal Cafe and Dining",
  "The restaurant has a great energy for group dining, the layout accommodates larger tables very well",
  "The kitchen here is clearly well managed because food comes out consistently excellent even on busy days",
  "Cleanliness of the restaurant is impeccable, tables are spotless and the overall hygiene standards are very high",
  "The staff is knowledgeable about the menu and gave genuinely helpful recommendations when we were undecided",
  "The live sports on TV made our dinner feel like a proper outing and everyone at the table was thoroughly entertained",
  "The waiting time is minimal even when the restaurant is busy, the kitchen clearly runs with great efficiency",
  "The atmosphere is relaxed and non-rushed which makes it ideal for long lunches and family dinners alike",
  "Every server we interacted with was polite, quick, and made the entire dining experience feel seamless",
  "The presentation of dishes is consistently attractive which adds to the overall dining experience significantly",
  "The restaurant feels premium without the stuffiness, the vibe is warm and genuinely welcoming at all times",
  "Royal Cafe and Dining strikes a perfect balance between casual dining energy and elevated food quality",
  "The comfort of the seating and the general ambience make it easy to relax and enjoy every bite",
  "The staff handled our large group effortlessly and made sure everyone was attended to at the same time",
  "The lighting inside is perfect for both casual dinners and celebratory occasions",
  "Even during peak hours the service quality does not drop, a sign of a very well-run restaurant",
  "The overall vibe at Royal Cafe and Dining is one of genuine hospitality and care for the guest experience",
  "The music selection is tasteful and adds to the ambience without being distracting during conversation",
  "Parking near IP Sigra Mall makes it very convenient to visit Royal Cafe and Dining even with family",
  "The portions here are genuinely generous and the pricing reflects outstanding value for the quality received",
  "The manager personally checked on our table mid-meal which showed a level of attentiveness rarely seen",
  "The decor inside is modern and well thought out, creating a warm environment that complements the food",
  "The air conditioning is perfectly calibrated, cool enough to be comfortable but not uncomfortably cold",
  "Every single order we placed was brought to the table correctly and promptly, zero errors across the entire meal",
  "The restrooms are clean and well-maintained which says a lot about the standards the restaurant holds itself to",
  "The cutlery and crockery are spotlessly clean and tastefully chosen, adding a premium feel to the dining experience",
  "Our server was patient and helpful when we had questions about ingredients, clearly knowing the menu inside out",
  "The background ambience is perfect for conversations, not too loud, not too quiet, exactly right",
  "The restaurant manages the rare feat of feeling upscale yet completely approachable at the same time",
  "Staff here treat every guest like a valued regular which creates an atmosphere of genuine warmth",
  "The location on the second floor of IP Sigra Mall gives the restaurant a lovely elevation and a great view",
  "Water was refilled promptly without us ever having to ask, a small detail that shows genuine attentiveness",
  "The menu is beautifully presented and easy to navigate, covering every cuisine section clearly and invitingly"
];

const SPECIAL_FEATURES = [
  "The anime figures and keychains on display are a delightful touch that anime fans will absolutely love",
  "As an anime fan I was thrilled to find a collection of anime figures and keychains at the restaurant, a truly unique concept",
  "The anime merchandise on display adds a fun and unique personality to Royal Cafe and Dining that sets it apart from any other restaurant in Varanasi",
  "Loved the anime figures on display, the owners have clearly thought about making this place special for fans beyond just the food",
  "The anime keychains available here are a charming souvenir and a fun surprise you do not expect to find in a restaurant",
  "Great discounts available through Dineout make Royal Cafe and Dining exceptional value for money every visit",
  "The Swiggy discounts they offer make ordering in from Royal Cafe and Dining an excellent deal as well",
  "Using EazyDiner here gives you a solid discount and makes a premium dining experience very accessible",
  "The RCD Special menu items are clearly the house favourites and every single one of them lives up to that reputation",
  "The Chef Special offerings like the 3 Idiot Paneer Tikka and Firni Faluda Shake are genuinely signature creations worth travelling for",
  "What I love most is that the menu is imaginative without trying too hard, every dish has a purpose and delivers on its promise",
  "The range of mocktails and shakes here is as exciting as the food menu, something for every palate and mood",
  "The dessert options at Royal Cafe and Dining are genuinely impressive especially the Choco Lava Cake and Jar Ice Creams",
  "The combination of Chinese, Tandoori, Biryani, Pizza, and Pasta on one menu executed this well is a remarkable achievement",
  "The Dineout tie-up means regular visitors can enjoy consistent savings which makes coming back an easy decision",
  "The anime theme in the decor is subtle and tasteful but deeply appreciated by fans who notice it",
  "Finding anime figures and keychains in a cafe setting in Varanasi is a first and it shows genuine creativity from the owners",
  "The variety on the menu ensures that no matter who you are dining with everyone will find something they love",
  "The drinks menu with creations like the Popcorn Caramel Latte and Passion Fruit Mojito shows real innovation",
  "The fact that both Swiggy and EazyDiner are available means you can enjoy Royal Cafe and Dining from the comfort of home too",
  "The special drinks like the Rasbhari Rasmalai Shake and Firni Faluda Shake are the kind of creations that become a reason to visit on their own",
  "The RCD Special menu is clearly a labour of love and every dish on it is genuinely outstanding",
  "The food quality maintains the same standard whether you dine in or order via Swiggy, which speaks to the kitchen's consistency",
  "What sets Royal Cafe and Dining apart is the thoughtful creativity in both the food and the overall concept of the place",
  "Anime fans visiting Varanasi will find Royal Cafe and Dining a particularly special destination, great food and great culture",
  "The Instagram-worthy plating at Royal Cafe and Dining makes every dish look as good as it tastes",
  "The Bamboo Biryani concept is something so uniquely creative that it alone is a reason to visit Royal Cafe and Dining",
  "The fact that Royal Cafe and Dining has maintained consistently high quality across such a diverse menu is genuinely extraordinary",
  "The family-friendly atmosphere combined with the premium food quality makes Royal Cafe and Dining suitable for every occasion",
  "The curated fusion of Banarasi tradition with global cuisine is what makes Royal Cafe and Dining truly one of a kind in Varanasi",
  "The Dineout deals combined with the consistent quality make Royal Cafe and Dining the most reliable dining choice in Sigra",
  "The fact that the kitchen produces outstanding biryani, excellent pizzas, and creative mocktails with equal skill is remarkable",
  "Royal Cafe and Dining has created a menu that is both familiar and surprising, an achievement very few restaurants manage"
];

const EVENTS_MENTIONS = [
  "Hosted my son's birthday party at Royal Cafe and Dining and the staff made sure every child had an absolutely wonderful time",
  "The restaurant is perfectly set up for kids birthday parties with great food, fun energy, and games to keep everyone entertained",
  "Our kitty party at Royal Cafe and Dining was a huge success, the food kept coming and the group was completely satisfied",
  "Celebrated our ring ceremony here and the staff went above and beyond to make the occasion truly special",
  "Had a marriage anniversary dinner at Royal Cafe and Dining and the atmosphere and food were both absolutely perfect for the occasion",
  "The private dining setup for celebrations is excellent and the staff coordinates group events with impressive professionalism",
  "Royal Cafe and Dining is easily the best spot in Sigra Varanasi for birthday parties and the kids absolutely loved it",
  "Our family get-together here was a complete success, the diverse menu ensured every family member found something they loved",
  "The team at Royal Cafe and Dining genuinely understands how to host celebrations without making it feel transactional",
  "Had our corporate team lunch at Royal Cafe and Dining and the food quality impressed even the most discerning colleagues",
  "The kitty party was a resounding success and every lady in the group has been raving about the food since",
  "Celebrated a promotion dinner here and the staff made sure the occasion felt properly special from start to finish",
  "The birthday setup for my daughter was everything she wanted and the Choco Lava Cake as a birthday dessert was a big hit",
  "Ring ceremony celebrations at Royal Cafe and Dining carry the right blend of elegance and warmth for such occasions",
  "Our anniversary dinner here was intimate and beautifully attended to, the food was exceptional and the service was discreet",
  "Birthday parties at Royal Cafe and Dining are special because the staff genuinely involves themselves in making memories",
  "From kitty parties to anniversary celebrations Royal Cafe and Dining handles every occasion with warmth and efficiency",
  "The restaurant accommodated our large joint-family gathering with ease and the food quality was consistent for every dish across the table",
  "Our office farewell lunch here was lovely and the team appreciated the gesture of choosing such a high quality restaurant",
  "The staff at Royal Cafe and Dining helped plan our table arrangement for the ring ceremony dinner and it was perfectly executed",
  "Kids absolutely enjoy the lively atmosphere here and the food options for children are genuinely enjoyable for young palates",
  "What makes celebrations at Royal Cafe and Dining special is that the staff treats your occasion as their own",
  "The combination of good food, a vibrant atmosphere, and TV entertainment makes it ideal for any group celebration",
  "Our anniversary was made memorable by the attention to detail and warmth that Royal Cafe and Dining consistently delivers",
  "For birthday parties in Varanasi this is genuinely the best option in Sigra and the feedback from guests confirms it every time",
  "Organized a surprise party for my wife at Royal Cafe and Dining and the staff helped coordinate everything perfectly",
  "Our college reunion dinner at Royal Cafe and Dining was the highlight of the entire reunion weekend",
  "The team handled our multi-generational family dinner with remarkable ease, catering to every age group's preferences",
  "Celebrating our daughter's achievement dinner at Royal Cafe and Dining made the occasion feel truly worth marking",
  "Our society's annual gathering was hosted at Royal Cafe and Dining and the unanimous verdict was to return next year too",
  "The engagement dinner we had at Royal Cafe and Dining was warmly received by both families and became a fond memory",
  "Friends visiting from outside Varanasi were taken to Royal Cafe and Dining and they left deeply impressed by the experience",
  "Our school reunion group chose Royal Cafe and Dining for our gathering and it was the best decision the committee made"
];

const CLOSING_RECS = [
  "Highly recommend Royal Cafe and Dining to anyone looking for a great dining experience in Varanasi.",
  "If you are in Sigra, Varanasi and want a genuinely excellent meal, Royal Cafe and Dining is your answer.",
  "The best restaurant in Sigra without any doubt. Every visit leaves you looking forward to the next one.",
  "Cannot recommend Royal Cafe and Dining highly enough. The food, service, and ambience are all exceptional.",
  "Five stars every single time. Royal Cafe and Dining has set a standard in Varanasi that is truly hard to match.",
  "Will keep coming back to Royal Cafe and Dining and will always recommend it to everyone without any hesitation.",
  "This is what dining out should feel like. Royal Cafe and Dining gets absolutely everything right.",
  "A gem on the second floor of IP Sigra Mall that every food lover in Varanasi needs to know about.",
  "100 percent recommended for families, groups, couples, and solo diners alike. Royal Cafe and Dining is for everyone.",
  "My favourite restaurant in Varanasi and once you visit you will understand exactly why. Highly recommended.",
  "Tell your friends, tell your family. A meal at Royal Cafe and Dining is an experience not to be missed.",
  "From the first bite to the last sip, Royal Cafe and Dining delivers an outstanding dining experience every time.",
  "Best food, best service, best vibe. Royal Cafe and Dining is genuinely the complete package.",
  "There is no finer dining experience in Sigra Varanasi than Royal Cafe and Dining. A truly outstanding restaurant.",
  "My only regret about Royal Cafe and Dining is that I did not discover it sooner. Absolutely unmissable.",
  "Whether you are a foodie, a family, or a group of friends, Royal Cafe and Dining will not let you down.",
  "Visit once and you will be a regular. Royal Cafe and Dining earns loyalty with every single dish it serves.",
  "The best dining decision you can make in Varanasi starts with booking a table at Royal Cafe and Dining.",
  "An institution in Sigra Varanasi for great food and great times. Royal Cafe and Dining is truly exceptional.",
  "Do not miss Royal Cafe and Dining if you are anywhere near Sigra. The food alone is worth the trip.",
  "The quality, care, and creativity at Royal Cafe and Dining make it the definitive restaurant of Sigra Varanasi.",
  "Strongly recommended to everyone in Varanasi looking for a restaurant that consistently delivers excellence.",
  "Once you try the food at Royal Cafe and Dining, every other restaurant in Varanasi will feel like a step down.",
  "Great food, great drinks, great people. Royal Cafe and Dining is simply the best the city has to offer.",
  "If Royal Cafe and Dining were anywhere else it would still be worth the drive. In Sigra it is simply unmissable.",
  "Year after year, visit after visit, Royal Cafe and Dining never disappoints. That consistency is their greatest achievement.",
  "Sincerely one of the best dining experiences I have had in Uttar Pradesh. Royal Cafe and Dining is extraordinary.",
  "Every single rupee spent at Royal Cafe and Dining feels well spent. Outstanding value for outstanding food.",
  "Go once, take your friends, bring your family. Royal Cafe and Dining will become everyone's favourite instantly.",
  "The food, the drinks, the ambience, and the people at Royal Cafe and Dining are all genuinely world-class.",
  "If you have not visited Royal Cafe and Dining yet, you are genuinely missing out on the best Sigra has to offer.",
  "My dining benchmark in Varanasi is now Royal Cafe and Dining and nothing else comes close.",
  "The kind of restaurant you leave already planning your next visit. Royal Cafe and Dining is that good.",
  "Trustworthy, delicious, and genuinely caring about the guest. Royal Cafe and Dining is everything a restaurant should be.",
  "Varanasi deserves a restaurant this good and Royal Cafe and Dining delivers it with pride and consistency.",
  "Not just recommended but genuinely celebrated. Royal Cafe and Dining is a true landmark of Sigra.",
  "Every time I am asked where to eat in Varanasi the answer is always Royal Cafe and Dining without any hesitation.",
  "The meals here leave you satisfied in a way that is rare. Royal Cafe and Dining is truly a cut above the rest.",
  "This restaurant has ruined other places for me in the best possible way. Royal Cafe and Dining is exceptional.",
  "A standing ovation to everyone at Royal Cafe and Dining for consistently delivering such extraordinary experiences."
];

const HI_OPENERS = [
  "Royal Cafe and Dining IP Sigra Mall mein pehli baar gaye aur experience absolutely amazing raha",
  "Kaafi time se sunte aa rahe the Royal Cafe and Dining ke baare mein, finally gaye aur bilkul satisfied hue",
  "Dost ne Royal Cafe and Dining suggest kiya tha Sigra mein, aur yeh suggestion life ki best tips mein se ek nikli",
  "Office ke saathi ne Royal Cafe and Dining mein lunch plan kiya aur poori team bahut khush hui",
  "Birthday party ke liye Royal Cafe and Dining choose kiya aur sab ne itna enjoy kiya ki next plan bhi wahi hai",
  "Swiggy par Royal Cafe and Dining dekha, dine-in ka plan banaya aur bilkul sahi decision tha",
  "IP Sigra Mall mein doosri manzil par Royal Cafe and Dining dekha, andar gaye aur bahut impressed hue",
  "Kitty party ke liye jagah dhundh rahe the aur Royal Cafe and Dining ne bilkul perfect experience diya",
  "Ring ceremony dinner ke liye Royal Cafe and Dining choose kiya aur poora parivaar bahut khush raha",
  "Anniversary dinner ke liye special jagah chahiye thi, Royal Cafe and Dining ne bilkul usi level ka experience diya",
  "EazyDiner pe discount dekhkar Royal Cafe and Dining mein booking ki, aur discount ke bina bhi worth it tha",
  "Teen logo ne Royal Cafe and Dining recommend kiya, teeno sahi the",
  "Ghar ke paas achha restaurant dhundh raha tha Sigra mein, Royal Cafe and Dining ne kisi ko bhi disappoint nahi kiya",
  "Bachche ke birthday ke liye Royal Cafe and Dining gaye aur wahan ka experience genuinely memorable raha",
  "Varanasi mein kuch alag taste karna tha, Royal Cafe and Dining ne wo zaroorat bilkul puri kar di",
  "Pehle sirf Swiggy se order kiya tha, phir dine-in kiya aur ab sirf wahi jaate hain",
  "Promotion celebrate karne ke liye friends ke saath Royal Cafe and Dining gaye, perfect choice tha",
  "Sasural wale aa rahe the, Royal Cafe and Dining le gaye aur unho ne bahut impressed feel kiya",
  "Varanasi mein itna diverse menu ek hi jagah dekhke khush ho gaye, Royal Cafe and Dining truly special hai",
  "Random weekend outing mein Royal Cafe and Dining try kiya aur ab yeh regular destination ban gayi hai",
  "Naya restaurant try karna tha Sigra mein aur Royal Cafe and Dining ne expectations se kahin zyada deliver kiya",
  "Joint family gathering ke liye Royal Cafe and Dining choose kiya aur sab generation ke log khush rahe",
  "Farewell lunch ke liye sabne milkar Royal Cafe and Dining choose kiya aur decision ekdum sahi raha",
  "Dineout par great deal dekhi aur Royal Cafe and Dining try kiya, value for money absolutely excellent tha",
  "College ke dost mile the kuch saalon baad, Royal Cafe and Dining mein meeting rachi aur evening yaadgaar bani",
  "Mahine mein do baar Royal Cafe and Dining jaana ab routine ban gayi hai, iska matlab kuch toh khaas hai",
  "Pehli baar family ke saath gaye the, ab parivaar khud yahi jaane ki demand karta hai",
  "Varanasi ke best restaurant ki list mein sabne Royal Cafe and Dining ka naam sabse pehle liya",
  "Khud try karke hi believe kiya ki Sigra mein itna achha restaurant hai, ab wahan ke bina koi celebration nahi",
  "First time Dineout se book kiya Royal Cafe and Dining mein, experience ne hamesha ke liye fan bana diya",
  "Bhai ki shaadi ki anniversary ke liye Royal Cafe and Dining gaye aur dono khush hoke ghar aaye",
  "Office party ke liye jagah dhundh rahe the, HR ne Royal Cafe and Dining suggest kiya aur sabne shukriya bola",
  "Instagram par Royal Cafe and Dining ke photos dekhke lalach aaya aur visit ne saaray expectations puri ki",
  "Neighbour ne insist kiya Royal Cafe and Dining try karne ko, aur ab main hi wahan ki sabse zyada tarif karta hoon",
  "Poori family ek saath bahar khana chahti thi, Royal Cafe and Dining ne sab ki pasand ka khayal rakha",
  "Beti ki result party ke liye Royal Cafe and Dining choose kiya aur usne khud bola yeh best evening thi uski zindagi ki",
  "Apni wife ko surprise dinner dena tha, Royal Cafe and Dining ne occasion ko bilkul perfect bana diya",
  "Kaafi mahine baad Varanasi aaya tha, pehla kaam Royal Cafe and Dining jaana tha aur woh feeling sahi nikli",
  "Naye ghar ki khushi mein grih pravesh party ke baad family ko Royal Cafe and Dining le gaye, sab khush rahe",
  "Pehle kaafi restaurants try kiye Sigra mein, Royal Cafe and Dining ne sab ko peeche chhod diya"
];

const HI_FOOD = [
  "3 Idiot Paneer Tikka ek baar khana zaroor chahiye, Varanasi ka best starter mila hai yahan",
  "Chicken Malai Tikka itna tender aur creamy tha ki ek plate mein poori mehfil khush ho gayi",
  "Drums of Heaven itne crispy aur addictive hain ki ek plate mein kaam nahi chalta, dusri plate bhi order ki",
  "Dahi Ke Kebab itne soft aur flavorful hain, kitchen ki genuine skill dikhate hain yeh kebab",
  "Paneer Malai Tikka bilkul melt-in-mouth tha, tandoor mein pakk ke aata hai toh alag hi baat ho jaati hai",
  "Hara Bhara Kebab fresh, vibrant aur well-spiced tha, vegetarians ke liye best starter option hai yeh",
  "Veg Seekh Kebab mein woh smoky char tha jo tandoor se aati hai, genuinely outstanding tha",
  "Stuffed Mushroom Tikka creative aur delicious tha, andar ki stuffing perfectly seasoned thi",
  "Chicken Seekh Kebab sizzling aaya aur juicy well-spiced mince ne sab ko speechless kar diya",
  "Afgani Soya Chaap itna rich aur creamy tha ki vegetarians bhi non-veg bhool jaate hain ek baar khake",
  "Chicken Afghani ka marinade subtle aur refined tha, genuinely excellent tandoori experience raha",
  "Veg Tandoori Platter ek hi plate mein poora tandoor section ka best dikha deta hai, RCD Special hai yeh",
  "Tandoori Chicken Platter mein char aur marinade dono outstanding the, crowd pleaser hai yeh",
  "Paneer Tikka ka mint chutney ke saath combination perfect tha, baar baar order karne wali cheez hai",
  "Chicken Lollipop ka glaze beautiful tha aur meat bilkul perfectly cooked tha right through",
  "Schezwan Crispy Chicken punchy tha aur sauce mein genuine depth thi, kisi bhi Chinese lover ke liye must-try",
  "Chicken 65 crispy, spicy aur perfect tha, classic dish ka best version mila hai yahan",
  "Crispy Honey Potato table par aate hi sab usi par toot pade, last piece ke liye haath ladh gaye",
  "American Corn Salt and Pepper light aur fresh tha, vegetarians ke liye brilliant starter option hai",
  "Cheese Balls golden aur gooey the, dipping sauce ke saath combination lajawab tha",
  "Paneer Kathi Roll well-spiced aur satisfying tha, roti wrap soft tha aur filling generous",
  "Chicken Kathi Roll mein marinated chicken aur fresh vegetables ka combination street-food vibes deta hai best tarah se",
  "Singapore Noodles ka wok char aur light spice bilkul perfect tha, ab yeh regular order ban gayi hai",
  "Chicken Hakka Noodles perfectly cooked the, clumped nahi, well-seasoned aur piping hot aaye",
  "American Chopsuey mein crispy noodle base ke saath jo gravy thi woh comfort food ka definition hai",
  "Chilli Garlic Noodles mein heat aur garlic ka balance sahi tha, aromatic without being overwhelming",
  "Pan Fried Noodles crispy edges ke saath soft centre, texture perfect tha aur flavour outstanding",
  "Chicken Manchurian ke balls tender aur crispy the, gravy rich aur tangy thi, bilkul sahi tha",
  "Garlic Chicken simple dish tha par deeply garlicky aur tender, execution ne star bana diya isse",
  "Lemon Garlic Chicken bright aur tangy tha, lighter Chinese option jo genuinely satisfying raha",
  "Chilli Paneer crisp bahar se, soft andar se, sauce mein spice aur tang ka balance perfect tha",
  "Chilly Mushroom bold sauce ke saath tha aur mushrooms ne apna texture retain kiya, bilkul sahi",
  "Schezwan Fried Rice punchy aur fragrant tha, vegetables clearly visible aur wok flavour outstanding",
  "Egg Fried Rice perfectly separated tha, bilkul greasy nahi aur seasoning spot-on thi",
  "Veg Chinese Combo fantastic value tha, noodles aur main dono mein best of both worlds mila",
  "Smoked Chicken Pizza itna achha tha ki dedicated pizza place se bhi better laga",
  "Chicken Cheese Burst Pizza ka cheese pull spectacular tha, naam se zyada deliver kiya is pizza ne",
  "Veg Cheese Burst Pizza perfectly baked tha, cheese burst centre indulgent aur delicious tha",
  "Smoked Paneer Pizza Chef Special hai aur smokiness beautifully execute ki gayi thi, creative aur tasty",
  "Tandoori Chicken Pizza mein Indian spices aur classic pizza flavours ka fusion brilliant tha",
  "Chicken Barbeque Pizza ka smoky sweet-tangy topping aur well-baked base lajawab combination tha",
  "Veg Barbeque Pizza mein toppings generous the aur barbeque sauce excellent, vegetarians ke liye must-try",
  "Spaghetti Aglio E Olio light aur garlicky tha, bilkul greasy nahi aur perfectly cooked",
  "Baked Penne Pasta comforting aur cheesy tha, sauce ki richness ne rok hi nahi paai khane se",
  "Club Chicken Triple Decker Sandwich massive aur generously filled tha, har layer mein flavour tha",
  "Veg Triple Decker Sandwich Chef Special hai aur fresh ingredients ke saath bhara hua tha, brilliant",
  "Paneer Tikka Sandwich tandoori flavours ko sandwich mein laata hai creatively, genuinely satisfying",
  "Chicken Tikka Sandwich well-seasoned aur fresh tha, lighter option jo flavour pe compromise nahi karta",
  "Veg Cheese Corn Sandwich simple comfort food tha, corn ki sweetness aur cheese ka melt perfect combination",
  "Murgh Handilazeez mein warmth aur complexity doni thi, slow cooking ka jaadu har spoonful mein feel hua",
  "Chicken Rara RCD Special hai aur gravy ki depth aur flavour genuinely outstanding tha",
  "Chef Chicken RCD Special menu ka star hai aur pehli baar aane walon ko zaroor try karna chahiye",
  "Mutton Rogan Josh aromatic, rich tha aur slow-cooked mutton bilkul fall-apart tender tha, exceptional",
  "Matka Mutton Biryani slow-cooked hai aur har nivaale mein flavour ka dhamaka tha, unforgettable",
  "Mutton Rara RCD Special hai aur gravy ka boldness aur complexity ek alag hi category mein aata hai",
  "Chicken Kali Mirch mein pepper ka taste bold tha par overpowering nahi, bahut achha balance tha",
  "Achari Murgh ki tangy pickle-spiced gravy genuinely unique thi, Garlic Naan ke saath combination perfect",
  "Palak Chicken mein spinach gravy fresh aur light thi, not too heavy aur beautifully executed dish",
  "Chicken Korma creamy aur subtly spiced tha, indulgent without being too rich, genuinely satisfying",
  "Chicken Butter Masala silky tha aur tomato base ki richness naan ke saath perfect pairing banti hai",
  "Chicken Lababdar mein charred onion-tomato gravy ki depth bahut achhi thi, flavour complex aur layered",
  "Kadai Chicken bold aur rustic tha, freshly ground masalas gravy mein zinda feel ho rahe the",
  "Chicken Dhaniya-adraki fragrant aur light tha, coriander aur ginger ka combination standout tha",
  "Mutton Curry slow-cooked the right way tha, spices integrated aur mutton wonderfully tender",
  "Palak Paneer smooth, well-seasoned tha aur real fresh ingredients taste mein clearly feel ho rahe the",
  "Paneer Hyderabadi mein spice aur richness ka balance bilkul sahi tha, genuine restaurant quality",
  "Paneer Butter Masala ki velvety tomato gravy rich par cloying nahi thi, beautifully balanced",
  "Shahi Paneer truly regal tha flavour mein, creamy gravy aur fresh soft paneer perfect combination",
  "Kadai Paneer mein capsicum aur tomatoes ka freshness clearly aaya, rustic aur wonderful",
  "Paneer Dhaniya-adraki fragrant aur lighter option tha, richer paneer gravies se refreshing change",
  "Malai Kofta itna creamy aur well-balanced tha ki seriously best version raha abhi tak",
  "Paneer Lababdar ki smoky charred gravy isse usual version se clearly different aur better banati hai",
  "Dal Palak healthy aur comforting tha, lentils aur spinach perfectly cooked together",
  "Punjabi Dal Tadka bilkul sahi tha, smoky tempering thick well-cooked dal ke upar, classic done right",
  "Corn Palak ek aisa combination tha jo pehle try nahi kiya tha, ab yeh favourite vegetarian dish ban gayi",
  "Mushroom Do Pyaza rich onion-forward mushroom dish tha, Lachha Paratha ke saath outstanding pairing",
  "Bhindi Masala perfectly cooked tha, okra slimy nahi thi bilkul aur masala wonderfully fragrant",
  "Aloo Jeera simple comfort food tha done brilliantly, tempering perfect aur potatoes just right",
  "Kashmiri Naan bilkul soft tha aur richer gravies ke saath combination lajawab raha",
  "Garlic Naan aur Murgh Handilazeez ka combination perfect tha, Firni Faluda Shake se end kiya, unforgettable meal",
  "Chicken Keema Kulcha hearty aur satisfying tha aur chutneys ke saath combination perfect tha",
  "Lachha Paratha perfectly layered tha, crispy bahar se aur soft andar, genuinely excellent bread",
  "Cheese Naan indulgent aur delicious tha, cheese andar beautifully melt hui aur bread perfectly cooked",
  "Missi Roti earthy aur flavourful thi, simple dals ke saath ise khana ek alag hi experience hai",
  "Stuffed Kulcha generously filled aur tandoor mein perfectly cooked tha, great bread option",
  "Bamboo Chicken Dum Biryani ki khushbu hi itni achhi hai ki order karna toh pakka hi hai",
  "Banarasi Soya Dum Biryani vegetarians ke liye bhi itna achha option hai ki non-veg yaad nahi aata",
  "Chicken Biryani dum-cooked properly tha, rice separated aur flavours deeply integrated",
  "Mutton Biryani layered aur aromatic tha aur mutton pieces throughout tender the, outstanding",
  "Kashmiri Pulao ka sweet-savoury combination menu par kisi bhi aur cheez se alag aur beautiful hai",
  "Hot N Sour Soup mein heat aur tang ka balance perfect tha, meal ka great starter",
  "Sweet Corn Soup comforting aur thick tha, well-seasoned, dusra bowl order karne ka mann kiya",
  "Manchow Soup mein crispy noodle topping aur deeply flavoured broth tha, best version around",
  "Cream of Tomato Soup silky aur rich tha, comfort in a bowl, any day ke liye perfect",
  "Lemon Coriander Soup light aur fresh tha, genuinely restorative aur perfect meal opener",
  "V Fries bilkul dangerously good hain, unique seasoning ke saath crispy, ek plate mein satisfy nahi hua",
  "Cheesy French Fries indulgent the aur generously loaded, cheese sauce thick aur perfectly seasoned",
  "Herby Cheese Garlic Bread ka herbed crust aur generous garlic butter perfect snack experience tha",
  "Cheese Chilli Toast mein green chillies ki heat aur cheese ka melt crisp toast par perfect tha",
  "Paneer Kurkure crispy, well-spiced aur addictive tha, cold frappe ke saath brilliant pairing",
  "Assorted Vegetable Pakodas golden aur crispy the, chutney ne unhe aur bhi elevate kiya",
  "Cafe Hazelnut beautifully aromatic tha aur hazelnut syrup not overpowering, perfectly balanced",
  "Popcorn Caramel Latte sach mein surprisingly good tha, concept quirky hai par result wonderful hai",
  "Irish Coffee properly made tha with genuine kick aur beautifully frothed cream on top",
  "Affogato classic precision ke saath bana tha, Espresso shot over ice cream perfectly executed",
  "Brownie Blended Coffee thick, rich aur indulgent tha, drink aur dessert dono ek saath",
  "Frappe With Cream And Cookies wonderfully indulgent tha, cookies ne har sip mein crunch add kiya",
  "Blended Mint Mocha refreshing aur creative tha, mint ne chocolate ko beautifully cut kiya",
  "Caramel Frappe thick, sweet aur perfectly blended tha, popular drink hai aur reason clear hai",
  "Hazelnut Frappe aromatic aur creamy tha, hazelnut flavour throughout without being artificial",
  "Peach Ice Tea refreshing aur light tha, heavier main course ke saath beautiful pairing",
  "Lychee Ice Tea delicate aur floral tha, Varanasi ke kisi bhi cafe mein best version yahi mila",
  "Hot Chocolate Truffle indulgent aur thick tha, regular hot chocolate se depth bahut zyada",
  "Ginger Honey Tea soothing aur perfectly balanced tha, kisi bhi meal ka perfect ending",
  "Assam Tea properly brewed, strong aur right temperature par serve hua, tea lovers ke liye must-order",
  "Firni Faluda Shake RCD ka signature creation hai aur ek baar peene ke baad bhool nahi paoge",
  "Red Velvet Shake thick aur indulgent tha, baaki sab bhoolwa deta hai ek baar peekar",
  "Rasmalai Lassi ek uniquely Banarasi creation hai, meetha aur thanda aur genuinely special",
  "Rasbhari Rasmalai Shake ek genius creation hai, dessert aur drink ek saath aur dono perfect",
  "Rose Faluda Shake beautifully floral tha, faluda ne texture add kiya aur rose flavour perfectly calibrated",
  "Masala Badam Shake warming, nutty aur spiced tha, menu par kisi bhi aur shake se alag category mein hai",
  "Mango Lassi thick aur pulpy tha with real mango flavour, classic done absolutely right",
  "Oreo Shake gloriously indulgent tha, Oreo crumble throughout the thick shake made every sip exciting",
  "Kulfi Shake traditional kulfi ka flavour perfectly capture kiya tha, brilliant fusion creation",
  "Kitkat Shake playful aur genuinely delicious tha with real Kitkat pieces blended throughout",
  "Banana Caramel Shake mein caramel sweetness aur banana ka combination outstanding dessert drink bana diya",
  "Coconut Shake fresh, light aur subtly sweet tha, richer shakes se refreshing change",
  "Fruit Punch Shake vibrant, colourful aur genuinely refreshing tha, lighter flavours prefer karne walon ke liye great",
  "Pinacolada Shake creamy aur tropical tha, har sip ke saath kahin aur pahunch jaate the",
  "Spicy Mango Mojito mein heat aur tang ka balance bahut achha tha, ghar ke baad bhi yaad aata hai",
  "Passion Fruit Mojito refreshing tha aur balanced, kisi bhi meal ke saath perfect pairing hai",
  "Blue Hawaiian visually stunning aur genuinely delicious tha, tropical sweetness irresistible thi",
  "Kala Khatta Mojito ek brilliant desi twist tha classic mojito par, jamun flavour bold aur nostalgic",
  "Watermelon Mojito light, fresh tha aur garam din mein genuinely cool feel karaya",
  "Green Apple Fizz crisp, tart aur most refreshing mocktail on the menu tha, har baar order karo",
  "Raspberry Mojito tart, sweet aur beautifully garnished tha, starters ke saath pairing lovely rahi",
  "Chilli Guava Mojito creative aur brilliant combination tha, guava sweetness with chilli heat inspired hai",
  "Masala Lemonade tangy, spiced aur perfectly balanced tha, wonderful desi mocktail",
  "Orange Blast refreshing aur vibrant tha, real orange flavour aur pleasant fizz throughout",
  "Hot Brownie Sizzler table par aaya toh sizzle ki awaaz ne hi poora dhyan kheench liya, pure indulgence",
  "Jar Ice Cream mein flavours itne achhe the ki last spoon se pehle hi dusra order karana chahte the",
  "Choco Lava Cake 99 rupaye mein milta hai aur lava flow har baar perfect tha, value toh dekho",
  "Gulab Jamun soft, perfectly soaked aur warm serve hue, classic dessert flawlessly executed",
  "Hot Brownie Sundae warm brownie, cold ice cream aur rich chocolate sauce, beautifully assembled dessert",
  "Brownie With Chocolate simple par perfectly executed tha, fudgy brownie aur genuinely rich chocolate sauce",
  "Masala Papad perfectly roasted tha with fresh onion-tomato topping, classic starter done right",
  "Pineapple Raita refreshing aur sweet tha, richer gravies ko balance karta hai beautifully",
  "Soya Chaap Tikka mein cream marinade aur perfect char ka combination genuinely outstanding tha",
  "Chicken Tikka Masala ki gravy itni silky aur flavourful thi ki naan khatam hone ka afsos hua",
  "Veg Crispy Noodles snack ke taur par itne achhe lage ki main course se pehle poori plate saaf ho gayi",
  "Peri Peri Chicken mein smoky heat bilkul sahi level par thi, ek dum satisfying experience tha",
  "Chicken Pasta white sauce mein creamy aur well-seasoned tha, pasta perfectly cooked al dente"
];

const HI_AMBIENCE = [
  "Restaurant ka ambience cosy aur welcoming hai, andar jaate hi comfortable feel hoti hai",
  "Staff bahut friendly hai aur genuinely attentive hai bina intrusive hue, bahut rare quality hai yeh",
  "TV par sports aur entertainment ka option hai toh khana khate khate match bhi dekh sakte ho",
  "Service prompt thi aur har dish sahi temperature par aayi, bahut restaurants yeh miss karte hain",
  "Interiors clean aur tastefully done hain, seating comfortable hai aur long meals ke liye bhi perfect",
  "Staff ne pehle wali visit se humare preferences yaad rakhe the, itna personal touch rare hai",
  "Har team member ka genuine smile aur warmth feel hota hai, forced nahi lagta ek bhi baar",
  "Entertainment screen par kuch na kuch chal raha hota hai toh wait time enjoyable ho jaata hai",
  "Pricing quality ke hisaab se bahut reasonable hai, value for money bahut achhi hai Royal Cafe mein",
  "Group dining ke liye layout bahut achha hai, badi tables easily accommodate ho jaati hain",
  "Busy days mein bhi kitchen consistent rehti hai, management clearly bahut achha hai",
  "Safarai aur hygiene standards impeccable hain, tables spotless hain aur environment clean hai",
  "Staff menu ke baare mein knowledgeable hai aur jab hum undecided the tab helpful suggestions di",
  "Live sports ne dinner ko ek complete outing jaisa feel karaya, sab enjoy karte rahe",
  "Wait time minimal hai even during rush hours, kitchen clearly efficiently chalti hai",
  "Atmosphere relaxed aur non-rushed hai, family dinners aur long lunches dono ke liye perfect",
  "Presentation of dishes consistently attractive hai, poore dining experience ko enhance karta hai",
  "Royal Cafe and Dining mein ek premium feel hai par stuffiness bilkul nahi, warmth aur care feel hoti hai",
  "Staff ne large group ko effortlessly handle kiya aur sab ko equally attend kiya",
  "Even peak hours mein service quality drop nahi hoti, sign hai ki management bahut strong hai",
  "Lighting perfect hai celebratory occasions aur casual dinners dono ke liye",
  "Seating comfortable hai aur general ambience aisa hai ki ghante baith ke baat karte raho",
  "Har baar jaao consistency maintain rehti hai food mein aur service mein bhi",
  "Hospitality genuinely feel hoti hai Royal Cafe and Dining mein, script follow nahi lagte staff",
  "IP Sigra Mall mein second floor par aana aur Royal Cafe and Dining mein ghusna ek genuinely good decision hai",
  "AC ka temperature perfect tha, na zyada thanda na zyada warm, bilkul comfortable experience",
  "Bartan aur cutlery spotlessly clean the, isse restaurant ke standards ka clearly pata chalta hai",
  "Crockery ka selection tasteful hai aur food presentation ko aur bhi attractive banata hai",
  "Restrooms clean aur well-maintained the, yeh detail bataati hai ki restaurant kitna seriously standards leta hai",
  "Manager ne khud table pe aake check kiya, itni personal attention bahut rare hai aaj kal",
  "Music ka selection sahi tha, background mein baj raha tha bina conversation disturb kiye",
  "Portions generous hain aur pricing ke hisaab se value genuinely outstanding hai",
  "Paani bina maange refill kiya staff ne, yeh chhoti si baat hi great service ka sabut hai",
  "Order placing se lekar last dish tak sab kuch seamless raha, zero confusion ya delay",
  "Har server ne apna kaam professionally kiya, ek bhi baar bura behavior ya attitude nahi dekha"
];

const HI_SPECIAL = [
  "Anime figures aur keychains dekh ke bilkul surprised ho gaye, ek restaurant mein yeh expect nahi kiya tha",
  "Anime fan hoon aur Royal Cafe and Dining mein anime figures dekh ke dil khush ho gaya, truly unique concept",
  "Anime keychains ek fun souvenir hain jo restaurant se milti hai, Varanasi mein kahi aur nahi milega yeh",
  "Dineout par great discounts available hain aur usse already achha experience aur bhi value ka ho jaata hai",
  "Swiggy se bhi order kiya hai aur dine-in quality hi milti hai, kitchen consistency bahut impressive hai",
  "EazyDiner discount ke saath Royal Cafe and Dining visit bahut wallet-friendly ho jaati hai",
  "RCD Special dishes sach mein signature creations feel hoti hain, har ek dish apna unique identity rakhti hai",
  "Chef Special menu mein 3 Idiot Paneer Tikka aur Firni Faluda Shake dono try karne chahiye, koi compromise nahi",
  "Menu itna diverse hai ki Chinese se Pizza se Biryani tak sab ek hi jagah perfect milta hai",
  "Drinks menu utna hi exciting hai jitna food menu, har mood ke liye kuch na kuch hai",
  "Desserts mein Choco Lava Cake aur Jar Ice Creams dono unmissable hain",
  "Dono Swiggy aur EazyDiner available hain toh ghar baith ke bhi Royal Cafe ka mazaa le sakte hain",
  "Anime theme subtle hai par anime fans ko turant pehchaan mein aa jaata hai, owners ne thought kiya hai",
  "RCD Special menu dekhkar lagta hai owners ne genuinely food ko seriously liya hai",
  "Special drinks jaise Rasbhari Rasmalai Shake aur Firni Faluda Shake khud mein ek reason hain aane ka",
  "Chinese food se lekar Banarasi Biryani tak sab ek hi kitchen se consistently excellent aata hai",
  "Anime figures aur keychains anime fans ke liye Royal Cafe and Dining ko Varanasi ka must-visit banaate hain",
  "Popcorn Caramel Latte jaise quirky drinks creativity dikhate hain jo standard restaurants mein nahi hoti",
  "Swiggy discounts ka matlab hai ki ghar se bhi Royal Cafe and Dining ka experience affordable ho jaata hai",
  "Menu ki creativity aur execution dono mein Royal Cafe and Dining genuinely best in class hai Sigra mein",
  "Bamboo Biryani concept itna unique hai ki Varanasi mein sirf Royal Cafe and Dining hi offer karta hai",
  "Dineout discount ke saath premium dining experience ka ek bhi rupaya zyada kharcha nahi lagta",
  "Instagram worthy presentation hai yahan, khana utna hi achha dikhta hai jitna khane mein lagta hai",
  "Banarasi traditions aur global cuisine ka fusion jo Royal Cafe and Dining karta hai woh truly exceptional hai",
  "Khane ki quality aur variety dono mein Royal Cafe and Dining ne Varanasi mein ek nayi standard set ki hai"
];

const HI_EVENTS = [
  "Bete ka birthday party Royal Cafe and Dining mein kiya aur bacchon ne itna enjoy kiya ki doobara wahi demand kiya",
  "Kitty party yahan ki thi aur poori group ne agree kiya ki best decision tha, khana zarbaar tha",
  "Ring ceremony dinner ke liye choose kiya aur staff ne occasion ko genuinely special feel karaya",
  "Anniversary dinner ke liye Royal Cafe and Dining gaye aur experience bilkul occasion ke level ka tha",
  "Bache ke liye birthday games aur achha khana dono ek jagah mila, Royal Cafe and Dining perfect hai",
  "Corporate team lunch yahan kiya aur sabne food ki quality se genuinely impressed feel kiya",
  "Farewell party yahan plan kiya aur food aur service ne occasion ko memorable bana diya",
  "Marriage anniversary celebration yahan tha aur atmosphere aur food dono ne occasion ko honour kiya",
  "Birthday party ke liye kids ne Choco Lava Cake demand kiya aur sab ke chehre dekhe the humne",
  "Family gathering ke liye Royal Cafe and Dining perfect jagah hai kyunki menu mein sab ko kuch na kuch milta hai",
  "Kitty group ne decide kiya tha ek special jagah try karni hai, Royal Cafe and Dining ne disappoint nahi kiya",
  "Staff ne ring ceremony dinner table arrangement mein genuinely help ki aur result perfect tha",
  "Birthday celebration yahan celebrate karna ek memorable experience tha, staff genuinely involved hua",
  "Promotion dinner ke liye dost le gaye aur evening itni achhi rahi ki dinner ke baad bhi baithe rahe",
  "College reunion ka plan Royal Cafe and Dining mein bana aur sab purani yaadein taaza ho gayi khate khate",
  "Engagement dinner yahan kiya aur dono families ne unanimously agree kiya ki jagah perfect thi",
  "School ke dosto se milne ka plan Royal Cafe and Dining mein bana, shaam raat ho gayi aur kisi ko ghar jaana nahi tha",
  "Office ki team building outing ke liye Royal Cafe and Dining choose kiya, team bonding bhi hua aur khana bhi lajawab tha",
  "Beti ki padhai ki safalta celebrate ki Royal Cafe and Dining mein, uski khushi dekhe ke layak thi",
  "Society gathering ke liye yahan booking ki aur sab ne unanimous decision liya ki agli baar bhi yahi aana hai"
];

const HI_CLOSE = [
  "Royal Cafe and Dining ko heartily recommend karunga har us insaan ko jo Varanasi mein achha khana chahta hai.",
  "Sigra Varanasi mein best restaurant hai Royal Cafe and Dining, kisi ko bhi doubt nahi hona chahiye.",
  "5 star se kam dena unfair hoga, food aur service dono mein yeh genuinely exceptional hai.",
  "Ek baar aaiye aur quality khud bol degi ki yeh Varanasi ki best dining destination kyun hai.",
  "Pehle kyun nahi aaya yeh regret zaroor hai, par ab Royal Cafe and Dining ke bina koi plan nahi banta.",
  "Apne saare doston aur parivaar ko already refer kar chuka hoon aur sab ne shukriya bola.",
  "Varanasi mein rehte ho aur achha khana chahte ho toh Royal Cafe and Dining se better koi option nahi.",
  "Food, ambience, staff, value sab mein top hai Royal Cafe and Dining, kisi ek mein bhi compromise nahi.",
  "Pehli visit ke baad hi pata chal gaya tha yeh jagah alag hai aur ab yeh opinion aur pakka ho gaya hai.",
  "Quality aur care jo Royal Cafe and Dining mein milti hai woh Varanasi ke kisi aur restaurant mein honestly nahi mili.",
  "Trusted and loved in Sigra Varanasi aur dil se kehta hoon yeh trust completely earned hai.",
  "Jab bhi Varanasi aao, Royal Cafe and Dining toh list mein rehna hi chahiye, koi argument nahi.",
  "Best dining decision Varanasi mein Royal Cafe and Dining jaana hai, seedha aao aur khud judge karo.",
  "Itna consistent quality maintain karna aasaan nahi hota, isliye Royal Cafe and Dining truly special hai.",
  "Dil se recommend karta hoon, ek baar try karo aur judge karo, zaroor disappointed nahi hoge.",
  "Varanasi ke har khane ke shauki ko Royal Cafe and Dining zaroor try karna chahiye, yeh ek baar ka nahi, baar baar aane wali jagah hai.",
  "Jo ek baar yahan aata hai woh wapas aata hai, yeh Royal Cafe and Dining ki sabse badi achievement hai.",
  "Pura Varanasi jaanta hai Royal Cafe and Dining kya hai, jo nahi jaanta woh sach mein kuch miss kar raha hai.",
  "Genuine khushi ke saath recommend karta hoon, yeh restaurant truly exceptional care ke saath chalaya ja raha hai.",
  "Apne favourite restaurant ki list mein Royal Cafe and Dining pehle number par hai aur yeh position kabhi badlegi nahi."
];

const ONE_LINERS_EN = [
  "Royal Cafe and Dining at IP Sigra Mall is the best restaurant in Varanasi. The 3 Idiot Paneer Tikka and Bamboo Chicken Dum Biryani alone are worth every visit. Exceptional food, friendly staff, and great Dineout deals.",
  "Have been a loyal visitor of Royal Cafe and Dining for months now and it has never once disappointed. The Firni Faluda Shake and Chef Chicken are signature dishes that you genuinely cannot get enough of.",
  "Royal Cafe and Dining is a hidden gem on the second floor of IP Sigra Mall. The Drums of Heaven, Matka Mutton Biryani, and the Choco Lava Cake at ninety-nine rupees are all absolutely unmissable.",
  "For anyone who loves great food in Varanasi, Royal Cafe and Dining delivers across Chinese, Tandoori, Biryani, Pizza, and Pasta with consistency that is genuinely rare to find.",
  "The staff at Royal Cafe and Dining is among the friendliest I have encountered in any restaurant in Varanasi. Combine that with outstanding food like the Smoked Chicken Pizza and V Fries and it is perfection.",
  "Royal Cafe and Dining is the complete package. Great food, great ambience, sports on TV, and as a bonus they even have anime figures and keychains on display for fans. Truly one of a kind.",
  "From the Spicy Mango Mojito to the Rasmalai Lassi to the Passion Fruit Mojito, the drinks menu at Royal Cafe and Dining is as creative and satisfying as the food menu. Highly recommend.",
  "Had our anniversary dinner at Royal Cafe and Dining and the Murgh Handilazeez with Garlic Naan was the highlight of the evening. Beautiful food and perfect service for a special occasion.",
  "Royal Cafe and Dining is our go-to for every celebration. Birthday parties, kitty parties, anniversaries, all handled with warmth, great food, and a genuinely fun atmosphere.",
  "The Jar Ice Creams and Hot Brownie Sizzler at Royal Cafe and Dining are desserts worth saving room for. The whole meal experience from starters to desserts is consistently excellent.",
  "Great discounts via Swiggy, Dineout, and EazyDiner make Royal Cafe and Dining already excellent value even better. The Chicken Rara and Chicken Kali Mirch are personal favourites.",
  "If I had to pick one restaurant in Varanasi to take someone who has never visited before, it would be Royal Cafe and Dining every single time. The quality and creativity are both outstanding.",
  "The Banarasi Soya Dum Biryani at Royal Cafe and Dining is a must for vegetarians and the Malai Kofta is creamy perfection. The kitchen genuinely delivers across every cuisine on the menu.",
  "Royal Cafe and Dining is not just a restaurant, it is an experience. The food, the anime decor, the sports TV, and the warm staff all come together to make something genuinely special.",
  "Dahi Ke Kebab and Crispy Honey Potato as starters followed by the Bamboo Chicken Dum Biryani. That is the Royal Cafe and Dining experience at its finest and it never lets you down.",
  "The Caramel Frappe and Brownie Blended Coffee at Royal Cafe and Dining are cold coffee creations that are exceptional. Pair them with the Paneer Kurkure and you have the perfect afternoon.",
  "Started with the Manchow Soup, ordered the Chicken Manchurian with Singapore Noodles, and finished with the Kulfi Shake. Every single course at Royal Cafe and Dining was outstanding.",
  "The Afgani Soya Chaap and Stuffed Mushroom Tikka are two vegetarian starters at Royal Cafe and Dining that honestly rival anything the non-veg section has to offer. Must-try items.",
  "From the Assam Tea in the morning to the Irish Coffee after dinner, the hot beverages at Royal Cafe and Dining are consistently excellent and brewed with real care.",
  "The Mutton Rogan Josh paired with Lachha Paratha and finished with a Rose Faluda Shake is the kind of meal at Royal Cafe and Dining that stays with you for days.",
  "The Chicken Cheese Burst Pizza and Veg Cheese Burst Pizza at Royal Cafe and Dining have cheese pulls that rival any dedicated pizzeria. The base is consistently well-baked every time.",
  "Hot N Sour Soup to start, Kadai Chicken with Cheese Naan for the main, and the Gulab Jamun to finish. Royal Cafe and Dining executes this classic combination flawlessly every time.",
  "The Kala Khatta Mojito and Chilli Guava Mojito are two mocktails at Royal Cafe and Dining that show how much thought goes into the drinks menu. Both are outstanding and completely unique.",
  "Blended Mint Mocha, Hazelnut Frappe, and Frappe with Cream and Cookies are just three of the brilliant cold coffees at Royal Cafe and Dining. The entire coffee menu is worth exploring thoroughly.",
  "The Chicken Afghani, Paneer Malai Tikka, and Hara Bhara Kebab from the tandoor section at Royal Cafe and Dining are all cooked with a level of skill and care that is genuinely impressive.",
  "Achari Murgh with Missi Roti and a Masala Badam Shake is an underrated combination at Royal Cafe and Dining that showcases the incredible range and depth of their kitchen.",
  "The American Chopsuey and Pan Fried Noodles at Royal Cafe and Dining are Chinese dishes executed with a confidence and skill that earns Royal Cafe and Dining its reputation as the best in Sigra.",
  "Every item on the RCD Special menu at Royal Cafe and Dining — from the Bamboo Biryani to the V Fries to the Chef Chicken — is a genuine signature creation that you cannot find anywhere else.",
  "The Lemon Coriander Soup, Schezwan Crispy Chicken, Palak Paneer with Stuffed Kulcha, and Hot Brownie Sundae. One perfect meal at Royal Cafe and Dining covers all four courses brilliantly.",
  "Sweet Corn Soup, Chicken Seekh Kebab, Mutton Curry with Garlic Naan, and a Mango Lassi to finish. Royal Cafe and Dining makes every single course of a meal memorable and satisfying.",
  "The Chicken Tikka Sandwich and Veg Triple Decker at Royal Cafe and Dining are standout lunch options that prove the kitchen is equally brilliant with lighter bites as it is with hearty mains.",
  "Palak Chicken with Kashmiri Naan followed by a Mango Lassi is one of those Royal Cafe and Dining combinations that feels both comforting and exciting at the same time.",
  "The Cheesy French Fries and Herby Cheese Garlic Bread at Royal Cafe and Dining are snack-time perfection. The Popcorn Caramel Latte makes it the ideal cafe afternoon out.",
  "Green Apple Fizz, Watermelon Mojito, and Blue Hawaiian — the mocktail lineup at Royal Cafe and Dining is creative enough to make the visit worthwhile even if you are not having a full meal.",
  "Mushroom Do Pyaza with Lachha Paratha at Royal Cafe and Dining is a vegetarian combination that satisfies completely. The Dal Tadka here is equally outstanding and beautifully smoky.",
  "The Pinacolada Shake and Coconut Shake at Royal Cafe and Dining are tropical escapes in a glass. Pair with the Spaghetti Aglio E Olio for a beautifully light yet satisfying meal.",
  "Chicken Dhaniya-adraki and Palak Paneer together on one table at Royal Cafe and Dining tell the whole story of a kitchen that genuinely understands how to balance fragrance and freshness.",
  "The Kashmiri Pulao at Royal Cafe and Dining is one of the most unique rice dishes available in Varanasi. Combined with the Shahi Paneer it creates an almost royal dining experience.",
  "Baked Penne Pasta and Smoked Paneer Pizza at Royal Cafe and Dining confirm that the Italian section of the menu is handled with the same care and skill as everything else. Outstanding.",
  "The Assorted Vegetable Pakodas and Cheese Chilli Toast at Royal Cafe and Dining are the kind of snacks that make you wonder why you ever ordered anything else to start a meal."
];

const ONE_LINERS_HI = [
  "Royal Cafe and Dining IP Sigra Mall mein Varanasi ka best restaurant hai. 3 Idiot Paneer Tikka aur Bamboo Chicken Dum Biryani toh sirf ek baar try karo aur phir khud bologe ki haan yeh best hai.",
  "Mahino se Royal Cafe and Dining ka regular hoon aur kabhi disappointing nahi hua. Firni Faluda Shake aur Chef Chicken signature dishes hain jinke bina visit incomplete lagti hai.",
  "Drums of Heaven, Matka Mutton Biryani, aur 99 rupaye mein Choco Lava Cake. Sirf yeh teeno dishes ke liye Royal Cafe and Dining jaana worth it hai.",
  "Staff itna friendly hai, khana itna achha hai, aur Dineout pe discount bhi milta hai. Royal Cafe and Dining Varanasi mein genuinely best dining experience hai.",
  "Chinese se lekar Biryani se lekar Pizza tak, Royal Cafe and Dining mein sab kuch ek hi level pe milta hai. Yeh consistency bahut rare hai aur isi liye yeh restaurant alag hai.",
  "Anime figures aur keychains ek restaurant mein milenge yeh socha nahi tha. Royal Cafe and Dining genuinely unique jagah hai Varanasi mein, food ke saath culture bhi milti hai.",
  "Birthday party ho ya kitty party ya anniversary, Royal Cafe and Dining har occasion ke liye perfect jagah hai. Staff genuinely help karta hai aur khana toh top class hai hi.",
  "Spicy Mango Mojito se lekar Popcorn Caramel Latte tak drinks menu utna hi exciting hai jitna food. Royal Cafe and Dining mein baar baar aane ka reason dhundne ki zaroorat nahi.",
  "V Fries, Club Chicken Triple Decker Sandwich, aur Rasmalai Lassi. Yeh teen cheezein pehli visit mein zaroor try karni chahiye Royal Cafe and Dining mein.",
  "Varanasi mein best restaurant ki baat ho toh seedha Royal Cafe and Dining ka naam aata hai. Quality, variety, aur service mein koi compromise nahi, har baar.",
  "Caramel Frappe aur Brownie Blended Coffee cold coffee section mein best options hain. Paneer Kurkure ke saath pair karo aur perfect afternoon ho jaati hai Royal Cafe and Dining mein.",
  "Manchow Soup se shuru kiya, Chicken Manchurian with Singapore Noodles khaaya, Kulfi Shake se khatam kiya. Har course outstanding tha Royal Cafe and Dining mein.",
  "Afgani Soya Chaap aur Stuffed Mushroom Tikka dono vegetarian starters itne amazing hain ki non-veg section yaad nahi aata. Must-try items hain Royal Cafe and Dining mein.",
  "Mutton Rogan Josh with Lachha Paratha aur Rose Faluda Shake ke saath end karo. Yeh combination Royal Cafe and Dining mein aisa meal hai jo days tak yaad rehta hai.",
  "Kala Khatta Mojito aur Chilli Guava Mojito dono unique aur outstanding mocktails hain. Drinks menu mein Royal Cafe and Dining ne genuine creativity dikhaayi hai.",
  "Achari Murgh with Missi Roti aur Masala Badam Shake ek underrated combination hai Royal Cafe and Dining mein jo kitchen ki range aur depth truly dikhata hai.",
  "Chicken Afghani, Paneer Malai Tikka, Hara Bhara Kebab - tandoor section ke yeh teeno dishes ek level ki care ke saath bane hain jo Varanasi ke kisi aur restaurant mein nahi mili.",
  "Lemon Coriander Soup, Schezwan Crispy Chicken, Palak Paneer with Stuffed Kulcha, aur Hot Brownie Sundae. Ek perfect meal ke charo courses Royal Cafe and Dining mein brilliantly covered hain.",
  "Hot N Sour Soup se start karo, Kadai Chicken with Cheese Naan main course mein lo, Gulab Jamun se finish karo. Royal Cafe and Dining yeh classic combination flawlessly execute karta hai.",
  "RCD Special menu pe har item - Bamboo Biryani se V Fries se Chef Chicken tak - ek genuine signature creation hai jo kahin aur nahi milti. Royal Cafe and Dining truly unique hai.",
  "Palak Chicken aur Kashmiri Naan ka combination Royal Cafe and Dining mein aisa hai jo baar baar order karne par majboor karta hai, Mango Lassi ke saath finish karo aur din ban jaata hai.",
  "Cheesy French Fries aur Herby Cheese Garlic Bread snack ke taur par perfect hain, aur Popcorn Caramel Latte ke saath Royal Cafe and Dining mein ek perfect cafe afternoon spend kar sakte ho.",
  "Green Apple Fizz, Watermelon Mojito, Blue Hawaiian - yeh teeno mocktails Royal Cafe and Dining mein itne achhe hain ki sirf drinks ke liye bhi yahan aana worth it hai.",
  "Mushroom Do Pyaza aur Lachha Paratha ka combination Royal Cafe and Dining mein vegetarians ke liye ek complete satisfying meal hai, Dal Tadka iske saath order karo toh aur bhi perfect.",
  "Baked Penne Pasta aur Smoked Paneer Pizza ek saath order karo Royal Cafe and Dining mein aur samjho ki Italian food bhi yahan utna hi phenomenal hai jitna Indian aur Chinese."
];

const TWO_PART_A = [
  "Royal Cafe and Dining at IP Sigra Mall is without question the most exciting restaurant in Varanasi right now.",
  "Have been visiting Royal Cafe and Dining regularly for months and the experience has been consistently excellent every single time.",
  "My culinary journey in Varanasi took a meaningful turn the first time I walked into Royal Cafe and Dining.",
  "The chef at Royal Cafe and Dining is clearly someone who takes genuine pride in every dish that leaves the kitchen.",
  "After trying several restaurants in Varanasi for a special occasion, Royal Cafe and Dining stood out by a significant margin.",
  "A friend's offhand recommendation led me to Royal Cafe and Dining and it completely changed how I think about dining in Varanasi.",
  "Cannot imagine celebrating any special occasion in Varanasi at any restaurant other than Royal Cafe and Dining.",
  "First visited Royal Cafe and Dining on a whim and ended up returning three times in the same month.",
  "The restaurant scene in Varanasi has many options but Royal Cafe and Dining is genuinely operating at a different level entirely.",
  "Have recommended Royal Cafe and Dining to everyone who has ever asked me where to eat in Sigra Varanasi.",
  "Came to Royal Cafe and Dining for the Bamboo Chicken Dum Biryani and left having discovered ten new favourite dishes.",
  "As someone very particular about food quality, finding a restaurant I could completely trust was difficult until Royal Cafe and Dining.",
  "The reputation of Royal Cafe and Dining for creative and consistent food is completely and entirely well-deserved.",
  "Started visiting Royal Cafe and Dining for one dish and gradually worked my way through almost the entire menu.",
  "The creativity at Royal Cafe and Dining reminded me of what restaurant dining should genuinely feel and taste like.",
  "From the moment I walked in, Royal Cafe and Dining communicated a very different and higher standard of dining.",
  "After years of eating at restaurants that let you down on delivery, Royal Cafe and Dining has consistently exceeded expectations.",
  "My sister's recommendation of Royal Cafe and Dining turned out to be one of the best food tips I have ever received.",
  "Never thought a restaurant in a mall in Varanasi would have this level of quality until I visited Royal Cafe and Dining.",
  "The first meal at Royal Cafe and Dining was more memorable and satisfying than I had any right to expect.",
  "The Firni Faluda Shake was the first thing I tried at Royal Cafe and Dining and it immediately told me this place was special.",
  "Booked through Dineout for a discount and ended up getting a dining experience that was worth far more than full price.",
  "The anime figures on display at Royal Cafe and Dining caught my eye first but the food is what made me stay and return.",
  "Our kitty group was undecided about a venue until someone suggested Royal Cafe and Dining and the decision was unanimous.",
  "Came for a birthday party and left genuinely amazed at how much thought and care Royal Cafe and Dining puts into every aspect.",
  "The Bamboo Chicken Dum Biryani at Royal Cafe and Dining is one of the most innovative dishes I have encountered in Varanasi.",
  "Three years of dining in Varanasi and nothing has come close to the consistently outstanding experience at Royal Cafe and Dining.",
  "The moment I saw the RCD Special menu at Royal Cafe and Dining I knew this restaurant thought about food differently.",
  "What drew me to Royal Cafe and Dining was curiosity but what kept me coming back is the extraordinary quality of every visit.",
  "Every anniversary, every birthday, every celebration in our family now automatically means booking at Royal Cafe and Dining.",
  "The Chicken Rara at Royal Cafe and Dining was a revelation on my first visit and remains my personal benchmark for that dish.",
  "Finding a restaurant that excels at both biryani and pizza in the same kitchen seemed impossible until Royal Cafe and Dining.",
  "The entire concept of Royal Cafe and Dining — the anime decor, the creative menu, the warm service — is genuinely original.",
  "My first impression of Royal Cafe and Dining was of a place that genuinely cared about its guests and the food proved it.",
  "The value for money at Royal Cafe and Dining, especially with Dineout and EazyDiner, is truly unmatched in Varanasi."
];

const TWO_PART_B = [
  "Every dish is prepared with genuine skill and the quality of ingredients is noticeably superior throughout the menu.",
  "The combination of creative dishes, warm service, and a vibrant ambience makes every visit feel genuinely special.",
  "The staff's knowledge of the menu and their enthusiasm for recommending dishes makes every order a confident one.",
  "From the first bite to the last sip, everything is handled with the kind of care that builds real loyalty.",
  "The custom RCD Special dishes like the Chef Chicken, Chicken Rara, and Firni Faluda Shake are precisely executed and always exceed expectations.",
  "The food quality has been consistent from the very first visit to every single one that has followed.",
  "This is genuinely the only restaurant in Varanasi where I would take someone important without any hesitation.",
  "The drinks menu spanning hot coffees, cold frappes, innovative shakes, and creative mocktails is as creative and satisfying as the food menu.",
  "Both the product quality and the overall dining experience here are truly exceptional in every single way.",
  "The entire journey from ordering to the last dessert is smooth, inspired, and genuinely satisfying from start to finish.",
  "This is what a restaurant should look like. Creative, quality-driven, and with the guest's experience at the centre of everything.",
  "No inflated promises, no rushed service, no compromises on ingredients. Just genuinely excellent food and honest hospitality.",
  "Years of passion and commitment to quality food come together perfectly at Royal Cafe and Dining.",
  "Highly recommended to every person in Varanasi who is serious about the quality of their dining experience.",
  "Will keep returning to Royal Cafe and Dining for every occasion. That is my most honest and confident verdict.",
  "The dishes speak louder than any words. Flavours this consistent and creative are genuinely rare to find anywhere in Varanasi.",
  "This level of culinary ambition and execution was something I associated with much larger cities until I found this place.",
  "Their commitment to creativity and quality over shortcuts — from the Bamboo Biryani to the Masala Badam Shake — makes every dish worth the visit.",
  "Everything from the tandoor section to the Chinese kitchen to the desserts reflects the highest standard of care and skill.",
  "My dining experiences in Varanasi have never been the same since discovering Royal Cafe and Dining, and entirely for the better.",
  "The range they pull off — Punjabi Dal Tadka alongside Baked Pasta, Mutton Rogan Josh alongside Spaghetti — and doing all of it well is remarkable.",
  "Whether you go for the Tandoori Chicken Platter, the Singapore Noodles, or the Veg Cheese Burst Pizza, the kitchen delivers every single time.",
  "The desserts here — Hot Brownie Sizzler, Jar Ice Cream, Gulab Jamun, Brownie Sundae — are the kind of ending to a meal that keeps you planning your next visit.",
  "The mocktail menu alone, with creations like the Blue Hawaiian, Kala Khatta Mojito, and Green Apple Fizz, is reason enough to visit Royal Cafe and Dining.",
  "The fact that the Assam Tea, Irish Coffee, and Affogato are all executed with the same care as the Biryani and Kebabs tells you everything about the kitchen's standards here.",
  "The attention to detail in every dish — from the perfectly separated Egg Fried Rice to the flawlessly dum-cooked Matka Biryani — is a signature of a truly dedicated kitchen.",
  "What sets Royal Cafe and Dining apart is not just individual great dishes but the consistency across an entire menu spanning multiple cuisines.",
  "The passion behind Royal Cafe and Dining is evident in every bowl, every plate, and every glass that arrives at your table.",
  "The warm and genuinely caring service at Royal Cafe and Dining elevates every meal into something that feels personal and memorable.",
  "A kitchen capable of producing the Chicken Kali Mirch and the Smoked Paneer Pizza with equal excellence is doing something truly special.",
  "The sheer joy of eating at Royal Cafe and Dining comes from knowing that every item you pick from the menu will genuinely deliver.",
  "The Varanasi food scene has a clear leader and its name is Royal Cafe and Dining. The quality speaks entirely for itself.",
  "From the first visit to the hundredth, Royal Cafe and Dining maintains the same extraordinary standard that made you fall in love with it.",
  "The combination of honest pricing, outstanding quality, and warm hospitality makes Royal Cafe and Dining the easiest recommendation in Varanasi.",
  "There is an unmistakable sense of pride in every plate at Royal Cafe and Dining, and that pride translates into exceptional flavour every time."
];

function rnd() { return Math.random(); }
function pick(a) { return a[Math.floor(rnd() * a.length)]; }

function compose() {
  var t = Math.floor(rnd() * 12);

  if (t === 0)  return pick(VISIT_OPENERS) + ". " + pick(FOOD_PRAISE) + ". " + pick(AMBIENCE_STAFF) + ". " + pick(CLOSING_RECS);
  if (t === 1)  return pick(VISIT_OPENERS) + ". " + pick(FOOD_PRAISE) + ". " + pick(SPECIAL_FEATURES) + ". " + pick(CLOSING_RECS);
  if (t === 2)  return pick(VISIT_OPENERS) + ". " + pick(EVENTS_MENTIONS) + ". " + pick(FOOD_PRAISE) + ". " + pick(CLOSING_RECS);
  if (t === 3)  return pick(VISIT_OPENERS) + ". " + pick(AMBIENCE_STAFF) + ". " + pick(SPECIAL_FEATURES) + ". " + pick(CLOSING_RECS);
  if (t === 4)  return pick(VISIT_OPENERS) + ". " + pick(FOOD_PRAISE) + ". " + pick(EVENTS_MENTIONS) + ". " + pick(CLOSING_RECS);
  if (t === 5)  return pick(ONE_LINERS_EN);
  if (t === 6)  return pick(ONE_LINERS_HI);
  if (t === 7)  return pick(TWO_PART_A) + " " + pick(TWO_PART_B);
  if (t === 8)  return pick(HI_OPENERS) + ". " + pick(HI_FOOD) + ". " + pick(HI_AMBIENCE) + ". " + pick(HI_CLOSE);
  if (t === 9)  return pick(HI_OPENERS) + ". " + pick(HI_FOOD) + ". " + pick(HI_SPECIAL) + ". " + pick(HI_CLOSE);
  if (t === 10) return pick(HI_OPENERS) + ". " + pick(HI_EVENTS) + ". " + pick(HI_FOOD) + ". " + pick(HI_CLOSE);
  var lines = [
    "Best restaurant in Sigra Varanasi. " + pick(FOOD_PRAISE) + ". " + pick(CLOSING_RECS),
    "Royal Cafe and Dining is in a league of its own for dining in Varanasi. " + pick(AMBIENCE_STAFF) + ". " + pick(CLOSING_RECS),
    pick(VISIT_OPENERS) + ". " + pick(SPECIAL_FEATURES) + ". " + pick(CLOSING_RECS),
    pick(AMBIENCE_STAFF) + ". " + pick(FOOD_PRAISE) + ". " + pick(CLOSING_RECS),
    pick(EVENTS_MENTIONS) + ". " + pick(FOOD_PRAISE) + ". " + pick(CLOSING_RECS),
    "Great food, great staff, great vibe. " + pick(SPECIAL_FEATURES) + ". " + pick(CLOSING_RECS),
    pick(FOOD_PRAISE) + ". " + pick(AMBIENCE_STAFF) + ". " + pick(CLOSING_RECS),
    pick(SPECIAL_FEATURES) + ". " + pick(EVENTS_MENTIONS) + ". " + pick(CLOSING_RECS),
    pick(HI_OPENERS) + ". " + pick(HI_FOOD) + ". " + pick(HI_EVENTS) + ". " + pick(HI_CLOSE),
    pick(HI_AMBIENCE) + ". " + pick(HI_SPECIAL) + ". " + pick(HI_CLOSE),
    pick(VISIT_OPENERS) + ". " + pick(FOOD_PRAISE) + ". " + pick(FOOD_PRAISE) + ". " + pick(CLOSING_RECS),
    pick(HI_OPENERS) + ". " + pick(HI_FOOD) + ". " + pick(HI_AMBIENCE) + ". " + pick(HI_SPECIAL) + ". " + pick(HI_CLOSE)
  ];
  return pick(lines);
}

export default function handler(req, res) {
  const generatedReview = compose();
  res.status(200).json({ review: generatedReview });
}
